server:
 port: 8085
spring:
  datasource:
   
    
    #Desarrollo 
    origen:
      jdbc-url: jdbc:sqlserver://131.1.0.137:1433;databaseName=INTELIBUS;encrypt=true;trustServerCertificate=true
      username: sa
      password: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      
    
    destino:
      jdbc-url: jdbc:sqlserver://131.1.0.130;databaseName=INTELIBUS;encrypt=true;trustServerCertificate=true
      username: sa
      password: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    
    origencard:
      jdbc-url: jdbc:sqlserver://131.1.0.129;databaseName=intelibus;encrypt=true;trustServerCertificate=true	
      username: sa
      password: sa
      drive-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      
  jpa:
   
   properties:
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    show-sql: true
  hibernate:
    ddl-auto: none  # Ajusta seg√∫n lo que necesites